name: Load Testing

on:
  workflow_dispatch:
    inputs:
      test_type:
        description: 'Test Type'
        required: true
        default: 'quick'
        type: choice
        options:
          - quick
          - 1500
          - distributed

jobs:
  quick-test:
    if: github.event.inputs.test_type == 'quick'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install
      
    - name: Install k6
      run: |
        sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C5AD17C747E3415A3642D57D77C6C491D6AC1D69
        echo "deb https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
        sudo apt-get update
        sudo apt-get install k6
        
    - name: Run Quick Test
      run: k6 run load-tests/quick-test.js --out json=quick-results.json
      
    - name: Generate Report
      if: always()
      run: node load-tests/enhanced-report-generator.js quick-results.json quick-report.html
        
    - name: Upload Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: quick-test-results
        path: |
          quick-results.json
          quick-report.html
        retention-days: 30

  test-1500:
    if: github.event.inputs.test_type == '1500'
    runs-on: ubuntu-latest
    timeout-minutes: 35
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install
      
    - name: Install k6
      run: |
        sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C5AD17C747E3415A3642D57D77C6C491D6AC1D69
        echo "deb https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
        sudo apt-get update
        sudo apt-get install k6
        
    - name: Run 1500 Users Test
      run: k6 run load-tests/optimized-1500-users.js --out json=1500-results.json
      
    - name: Generate Report
      if: always()
      run: node load-tests/enhanced-report-generator.js 1500-results.json 1500-report.html
        
    - name: Upload Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: 1500-test-results
        path: |
          1500-results.json
          1500-report.html
        retention-days: 30

  distributed-test:
    if: github.event.inputs.test_type == 'distributed'
    runs-on: ubuntu-latest
    timeout-minutes: 35
    strategy:
      matrix:
        instance: [1, 2, 3]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install
      
    - name: Install k6
      run: |
        sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C5AD17C747E3415A3642D57D77C6C491D6AC1D69
        echo "deb https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
        sudo apt-get update
        sudo apt-get install k6
        
    - name: Run Distributed Test
      run: k6 run load-tests/distributed-runner.js --out json=distributed-${{ matrix.instance }}-results.json
      
    - name: Upload Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: distributed-${{ matrix.instance }}-results
        path: distributed-${{ matrix.instance }}-results.json
        retention-days: 30

  summary:
    runs-on: ubuntu-latest
    needs: [quick-test, test-1500, distributed-test]
    if: always()
    
    steps:
    - name: Generate summary
      run: |
        echo "## Load Test Results Summary" >> $GITHUB_STEP_SUMMARY
        echo "- Test Type: ${{ github.event.inputs.test_type }}" >> $GITHUB_STEP_SUMMARY
        echo "- Status: ${{ needs.quick-test.result || needs.test-1500.result || needs.distributed-test.result }}" >> $GITHUB_STEP_SUMMARY
        echo "- Results available in artifacts" >> $GITHUB_STEP_SUMMARY 